name: A7x-Syn
description: 'Seize the day'
meta_description: "Yeeee---"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 20
domain_name: 'https://github.com/A7x-synm'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'https://a7x-syn.github.io/'
author:         'DNA'
authorTwitter:  '1h_03'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
