# Site Info
title: Seize The Day
tagline: 'A7X'
description: ''
baseurl: ""
url: http://A7x-syn.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.1.1

# About/contact
author:
  name: 1H3M
  description: 최고다 밋치
  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    # linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/A7x-syn
    # facebook:  <hide>
    twitter:   https://twitter.com/R_tinkyWinky
    # email:     matilto:kimdana741@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'http://A7x-syn.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/mainPicture.png
  caption: The harder you work, the more likely you can reach the goal.

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'your_short_name' # leave blank if you don't want disqus

# 블로그 검색
 tipue_search:
     include:
         pages: false
         collections: []
     exclude:
         files: [search.html, index.html]
         categories: []
         tags: []
